defaults:
  - datamodule: av2  
  - model: model_forecast  

hydra:
  run:
    dir: outputs/${output}/${now:%Y%m%d-%H%M%S}

seed: 2026
monitor: val_minFDE6
save_top_k: 10

data_root:
checkpoint:
pretrained_weights:
output: change_${datamodule.name}_${datamodule.phase}_${model.name}_${model.phase}

# trainer
num_workers: 4
gpus: 1  # when test, only use 1 gpu; when train/val, use 8 gpus
sync_bn: true
batch_size: 160
epochs: 60
warmup_epochs: 5
ws_offset: [1.0, 1.0]

enc_layer_1: 4
enc_layer_2: 2

dec_layer_1: 2
dec_layer_2: 2
t_per_tok: 10

# optimizer
lr: 2e-4
weight_decay: 1e-4
gradient_clip_val: 1.0
gradient_clip_algorithm: norm

limit_train_batches:
limit_val_batches:
limit_test_batches:
log_model: all
test: false  # false for val, true for test
