defaults:
  - datamodule: av2  
  - model: model_forecast  

hydra:
  run:
    dir: outputs/${output}/${now:%Y%m%d-%H%M%S}

seed: 2024
monitor: val_minFDE6
save_top_k: 10

data_root:
checkpoint:
pretrained_weights:
output: change_${datamodule.name}_${datamodule.phase}_${model.name}_${model.phase}

# trainer
num_workers: 16
gpus: 1  # Paper: 10x RTX A5000; test/inference: 1 GPU
sync_bn: false
batch_size: 160
epochs: 60
warmup_epochs: 10
ws_offset: [0.0, 1.0]  # only RP2 supervised

enc_layer_1: 4
enc_layer_2: 2

dec_layer_1: 2  # TEDec: 2+4=6 CAM blocks (supplementary)
dec_layer_2: 4

# optimizer
lr: 0.0015
weight_decay: 1e-2  
gradient_clip_val: 5
gradient_clip_algorithm: norm

limit_train_batches:
limit_val_batches:
limit_test_batches:
log_model: all
test: false  # false for val, true for test
