import torch
import abc
from typing import Dict, Union
import torch.nn as nn
import torch.nn.functional as F


class Metric:
    """
    Base class for prediction metric/loss function
    """
    @abc.abstractmethod
    def __init__(self):
        raise NotImplementedError()

    @abc.abstractmethod
    def compute(self, predictions: Union[torch.Tensor, Dict], ground_truth: Union[torch.Tensor, Dict]) -> torch.Tensor:
        """
        Main function that computes the metric
        :param predictions: Predictions generated by the model
        :param ground_truth: Ground truth labels
        :return metric: Tensor with computed value of metric.
        """
        raise NotImplementedError()
    

class LaplaceNLLLoss(Metric):
    """
    Negative log likelihood loss for ground truth goal nodes under predicted goal log-probabilities.
    """
    def __init__(
        self,
        num_modes: int = 6,
        top_m: int = 2,
        tau: float = 0.7,
        detach_soft_weight: bool = True,
        scale_min: float = 1e-3,
        scale_max: float = 10.0,
        cls_weight: float = 0.5,
    ):
        self.name = 'LaplaceNLLLoss'
        self.loss = nn.SmoothL1Loss(reduction='mean')
        self.num_modes = num_modes
        self.top_m = top_m
        self.tau = tau
        self.detach_soft_weight = detach_soft_weight
        self.scale_min = scale_min
        self.scale_max = scale_max
        self.cls_weight = cls_weight

    def _build_soft_targets(self, mode_dist: torch.Tensor) -> torch.Tensor:
        top_m = min(self.top_m, mode_dist.size(1))
        top_dist, top_idx = torch.topk(mode_dist, k=top_m, dim=-1, largest=False)
        weights = F.softmax(-top_dist / max(self.tau, 1e-6), dim=-1)
        if self.detach_soft_weight:
            weights = weights.detach()
        soft_target = torch.zeros_like(mode_dist)
        soft_target.scatter_(1, top_idx, weights)
        return soft_target

    def compute(self, predictions: Dict, ground_truth: Union[torch.Tensor, Dict]) -> torch.Tensor:
        out_mu = predictions['traj']
        out_sigma = predictions['scale']
        out_pi = predictions['probs']
        gt = ground_truth

        if out_mu is None or out_sigma is None or out_pi is None:
            return gt.new_tensor(0.0)

        gt_expanded = gt.unsqueeze(1)
        mode_dist = torch.norm(
            out_mu[..., -1, :2] - gt_expanded[..., -1, :2], p=2, dim=-1
        )
        soft_target = self._build_soft_targets(mode_dist)

        scale = out_sigma.clamp(min=self.scale_min, max=self.scale_max)
        nll = torch.log(2 * scale) + torch.abs(gt_expanded - out_mu) / scale
        nll_per_mode = nll.mean(dim=(-1, -2))
        nll_loss = (soft_target * nll_per_mode).sum(dim=-1).mean()

        cls_loss = -(soft_target * F.log_softmax(out_pi, dim=-1)).sum(dim=-1).mean()

        return nll_loss + self.cls_weight * cls_loss
